version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php-fpm-sergey
    expose:
      - 9000  # Expose PHP-FPM port
    volumes:
      - ..:/app
    networks:
      - app-network

  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    container_name: nginx-sergey
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ..:/app
    depends_on:
      - web
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
